default:
    image: python:3.7-buster 

stages:
  - test
  - deploy

python:
  stage: test
  script:
    - apt-get update -qq && apt-get install -y -qq tox
    - tox -e cov-init,py3,cov-report
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
  artifacts:
    paths:
      - coverage_html_report
    expire_in: 1 day

code_analysis:
  stage: test
  script:
    - python3 -m pip install -r requirements/test.txt
    - python3 -m pylint src
  allow_failure: true

deploy_production:
  stage: deploy
  script:
    - python3 -m pip install -U twine
    - python3 setup.py sdist bdist_wheel
    # Upload to the public PyPI index - assumes env variable TWINE_PASSWORD
    # is set to the API token
    - TWINE_USERNAME=__token__ python -m twine upload dist/*
  only:
    - master

pages:  
  stage: test
  script:
  - cd docs
  - pip install -r requirements.txt
  - ./generate_docs.sh
  - mv _build ../public
  artifacts:
    paths:
    - public

